emergency_settings:
  current_limit: 268
  temperature_limit: 989
  voltage_LN_limit: 863
resistor_settings:
  r1: 92.12
  r10: 5.53
  r11: 5.45
  r12: 5.56
  r2: 46.28
  r3: 43.76
  r4: 22.88
  r5: 21.73
  r6: 22.47
  r7: 10.99
  r8: 11.19
  r9: 11.24
resistor_threshold_allow:
  max: 20
  min: 20
