emergency_settings:
  current_limit: 268
  temperature_limit: 989
  voltage_LN_limit: 863
resistor_settings:
  r1: 134.23
  r10: 8.26
  r11: 8.09
  r12: 8.28
  r2: 64.36
  r3: 65.94
  r4: 33.35
  r5: 33.41
  r6: 33.41
  r7: 15.98
  r8: 15.97
  r9: 16.25
resistor_threshold_allow:
  max: 20
  min: 20
