emergency_settings:
  current_limit: 268
  temperature_limit: 989
  voltage_LN_limit: 863
resistor_settings:
  r1: 132
  r10: 8.4
  r11: 8.2
  r12: 8.4
  r2: 64
  r3: 64
  r4: 34
  r5: 33
  r6: 33
  r7: 16
  r8: 16
  r9: 16
resistor_threshold_allow:
  max: 20
  min: 20
